#ifndef __OUTPUT_H
#define __OUTPUT_H
#include "flash.h"
#define FLASH_HANDLE_TIME 5
#define DATA_SIZE 2
#define FLASH_MENBER 11

/* 主存储地址 */
#define A_LAST_DIRECT_SET_TEMP_ADDRESS (0x08000000 + 1024 * 254)
#define A_LAST_DIRECT_SET_CAL_TEMP A_LAST_DIRECT_SET_TEMP_ADDRESS + DATA_SIZE
#define A_LAST_TEMP_UINT A_LAST_DIRECT_SET_CAL_TEMP + DATA_SIZE
#define A_LAST_SPEAK_STATE A_LAST_TEMP_UINT + DATA_SIZE
#define A_LAST_DISPLAY_LOCK_STATE A_LAST_SPEAK_STATE + DATA_SIZE
#define A_LAST_CH1_SET_TEMP A_LAST_DISPLAY_LOCK_STATE + DATA_SIZE
#define A_LAST_CH2_SET_TEMP A_LAST_CH1_SET_TEMP + DATA_SIZE
#define A_LAST_CH3_SET_TEMP A_LAST_CH2_SET_TEMP + DATA_SIZE
#define A_LAST_SET_SLEEP_TIME A_LAST_CH3_SET_TEMP + DATA_SIZE
#define A_LAST_SHOW_MODE_ADDRESS A_LAST_SET_SLEEP_TIME + DATA_SIZE
#define A_LAST_LANGUAGE_STATE_ADDRESS A_LAST_SHOW_MODE_ADDRESS + DATA_SIZE
#define A_FLASH_VERSION_ADDRESS A_LAST_LANGUAGE_STATE_ADDRESS + DATA_SIZE


/* 备份地址 */
#define B_LAST_DIRECT_SET_TEMP_ADDRESS (0x08000000 + 1024 * 255)
#define B_LAST_DIRECT_SET_CAL_TEMP B_LAST_DIRECT_SET_TEMP_ADDRESS + DATA_SIZE
#define B_LAST_TEMP_UINT B_LAST_DIRECT_SET_CAL_TEMP + DATA_SIZE
#define B_LAST_SPEAK_STATE B_LAST_TEMP_UINT + DATA_SIZE
#define B_LAST_DISPLAY_LOCK_STATE B_LAST_SPEAK_STATE + DATA_SIZE
#define B_LAST_CH1_SET_TEMP B_LAST_DISPLAY_LOCK_STATE + DATA_SIZE
#define B_LAST_CH2_SET_TEMP B_LAST_CH1_SET_TEMP + DATA_SIZE
#define B_LAST_CH3_SET_TEMP B_LAST_CH2_SET_TEMP + DATA_SIZE
#define B_LAST_SET_SLEEP_TIME B_LAST_CH3_SET_TEMP + DATA_SIZE
#define B_LAST_SHOW_MODE_ADDRESS B_LAST_SET_SLEEP_TIME + DATA_SIZE
#define B_LAST_LANGUAGE_STATE_ADDRESS B_LAST_SHOW_MODE_ADDRESS + DATA_SIZE
#define B_FLASH_VERSION_ADDRESS B_LAST_LANGUAGE_STATE_ADDRESS + DATA_SIZE

typedef enum
{
	FLASH_START = 0,
	FLASH_HANDLE_DATA,
	FLASH_GENERAL_DATA,
	FLASH_FINSH,
} flash_state_t;

typedef struct
{
	flash_state_t state;
} flash_handle_t;

void FlashProc(void);

#endif
