#ifndef _KEY_HANDLE_H
#define _KEY_HANDLE_H
#include "key.h"
#define KEY_HANDLE_TIME 10
#include "stdbool.h"
#define KEY_TASK_TIME          20
typedef enum
{
	TEMP_ADD = 0,
	TEMP_ADD_FIVE,
	TEMP_REDUCE,
	TEMP_REDUCE_FIVE,
	TIME_COUNTDOWN_EVENT,
	VALUE_RESET_EVENT,

	ENTER_MENU,
	ENTER_SETS,
	PAGE_ADD,
	PAGE_REDUCE,
	EXIT_MENU,
	
	GET_CHANNEL_1,
	GET_CHANNEL_2,
	GET_CHANNEL_3,
	CHANGE_CH,
	SET_CHANNEL_1,
	SET_CHANNEL_2,
	SET_CHANNEL_3,

	SET_WORK_MODE,
	SET_TEMP_UNIT,

	SELECT_CAL,
	SELECT_NONE_CAL,
	SET_CAL_TEMP_ADD,
	SET_CAL_TEMP_REDUCE,
	SET_CAL_TEMP_ADD_FIVE,
	SET_CAL_TEMP_REDUCE_FIVE,

	SET_SPEAK_MODE,
	SET_TEMP_LOCK,

	SELECT_SLEEP,
	SELECT_NONE_SLEEP,
	SET_SLEEP_TIME_ADD,
	SET_SLEEP_TIME_REDUCE,
	SET_SLEEP_TIME_ADD_FIVE,
	SET_SLEEP_TIME_REDUCE_FIVE,
	SET_RESET,
	RESET_BE02_VALUE,
	SET_LANGUAGE_MODE,
	
	END_EVENT,

} handle_event;

void key_handle(void);
#endif
